// ── PRODUCT DATA ──
const PRODUCTS = [
  { id:1, name:'VedaProtein Elite Whey', category:'Protein Powders', catKey:'protein', emoji:'💪', badge:'Best Seller', price:1299, mrp:1599, rating:5, reviews:128, desc:'24g protein per scoop. Mixes instantly. Chocolate & Vanilla flavors. Ideal for muscle recovery.', benefits:['24g Protein per serving','Zero added sugar','Digestive enzyme blend','Chocolate & Vanilla flavors','30 servings per pack'], tags:['Whey Protein','Muscle Gain','Post-Workout'] },
  { id:2, name:'PlantPower Vegan Protein', category:'Protein Powders', catKey:'protein', emoji:'🌱', badge:'New', price:1099, mrp:1299, rating:4.8, reviews:64, desc:'100% plant-based pea & brown rice blend. 20g protein. Vegan & lactose-free.', benefits:['20g Plant Protein','Pea + Brown Rice Blend','Vegan & Lactose-Free','No Artificial Colours','Unflavored & Vanilla'], tags:['Plant Protein','Vegan','Lactose-Free'] },
  { id:3, name:'Daily Vitality Multivitamin', category:'Vitamins & Supplements', catKey:'vitamins', emoji:'☀️', badge:'Popular', price:699, mrp:899, rating:4.9, reviews:203, desc:'Complete daily multivitamin with Vitamin D3, B12, Zinc & Iron. 60 capsules per pack.', benefits:['Vitamin D3 + K2','Vitamin B12 & B-Complex','Zinc & Selenium','Iron for energy','60-day supply'], tags:['Multivitamin','Daily Health','Immunity'] },
  { id:4, name:'OmegaVeda Fish Oil', category:'Vitamins & Supplements', catKey:'vitamins', emoji:'🐟', badge:'Trending', price:549, mrp:699, rating:4.7, reviews:87, desc:'High-strength Omega-3 EPA & DHA. Supports heart, brain & joint health. Lemon flavored.', benefits:['1000mg Omega-3 per capsule','EPA + DHA blend','Heart & Brain support','No fishy aftertaste','90 softgels'], tags:['Omega-3','Heart Health','Brain Health'] },
  { id:5, name:'AshwaBalance Herbal Blend', category:'Herbal Blends', catKey:'herbal', emoji:'🌿', badge:'Ayurvedic', price:549, mrp:699, rating:4.8, reviews:95, desc:'Ashwagandha + Brahmi + Shatavari. Stress relief, hormonal balance & mental clarity.', benefits:['KSM-66 Ashwagandha','Brahmi for focus','Shatavari for balance','Adaptogenic formula','60 veg capsules'], tags:['Stress Relief','Adaptogen','Hormonal Balance'] },
  { id:6, name:'TurmerCure Gold Blend', category:'Herbal Blends', catKey:'herbal', emoji:'🔥', badge:'Anti-Inflammatory', price:449, mrp:599, rating:4.9, reviews:144, desc:'Turmeric + Black Pepper + Ginger. Powerful anti-inflammatory & immunity booster.', benefits:['95% Curcumin extract','BioPerine for absorption','Ginger root extract','Anti-inflammatory','Immunity support'], tags:['Turmeric','Anti-Inflammatory','Immunity'] },
  { id:7, name:'GrowStrong Kids NutriMix', category:'Kids Nutrition', catKey:'kids', emoji:'💛', badge:'Kids Fav', price:649, mrp:799, rating:5, reviews:176, desc:'For children 2–12 years. DHA, Calcium, Iron & essential vitamins for growth and energy.', benefits:['DHA for brain development','Calcium + Vitamin D','Iron for energy','Prebiotic fibre','Chocolate & Mango flavor'], tags:['Kids 2-12','Brain Development','Growth'] },
  { id:8, name:'JuniorImmune Chewables', category:'Kids Nutrition', catKey:'kids', emoji:'🍊', badge:'Doctor Approved', price:449, mrp:599, rating:4.8, reviews:112, desc:'Chewable tablets with Vitamin C, Zinc, Elderberry & Echinacea for kids\' immunity.', benefits:['Vitamin C 250mg','Zinc for immunity','Elderberry extract','Echinacea blend','30 chewable tablets'], tags:['Kids Immunity','Chewable','Vitamin C'] },
  { id:9, name:'Casein NightRecovery', category:'Protein Powders', catKey:'protein', emoji:'🌙', badge:'Night Protein', price:1399, mrp:1699, rating:4.7, reviews:58, desc:'Micellar casein for slow-release overnight muscle recovery. 25g protein per serving.', benefits:['25g Micellar Casein','Slow-release 7–8 hrs','Overnight recovery','Rich Chocolate flavour','30 servings'], tags:['Casein','Night Protein','Recovery'] },
  { id:10, name:'VitaminD3 + K2 Drops', category:'Vitamins & Supplements', catKey:'vitamins', emoji:'🌞', badge:'Essential', price:349, mrp:499, rating:4.9, reviews:201, desc:'Liquid D3 + K2 drops. 2000IU Vitamin D3 with Vitamin K2 MK-7 for calcium absorption.', benefits:['2000IU Vitamin D3','Vitamin K2 MK-7','Liquid for fast absorption','Unflavored drops','60-day supply'], tags:['Vitamin D3','Bone Health','Immunity'] },
  { id:11, name:'TriphalaDetox Blend', category:'Herbal Blends', catKey:'herbal', emoji:'🍃', badge:'Detox', price:399, mrp:549, rating:4.6, reviews:79, desc:'Classic Triphala — Amla, Haritaki, Bibhitaki. Gentle detox, digestion & gut health.', benefits:['Amla + Haritaki + Bibhitaki','Gut health support','Gentle daily detox','Antioxidant rich','90 veg capsules'], tags:['Triphala','Gut Health','Detox'] },
  { id:12, name:'GrowTall Kids Calcium+', category:'Kids Nutrition', catKey:'kids', emoji:'🦴', badge:'Height & Bone', price:549, mrp:699, rating:4.7, reviews:93, desc:'Calcium + Vitamin D3 + Magnesium formula for growing kids. Supports height & bone density.', benefits:['500mg Calcium per serving','Vitamin D3 for absorption','Magnesium for bone strength','Ages 5–15','Vanilla flavour'], tags:['Calcium','Bone Health','Growth'] },
  
  // ── NUTRIVEDA SPECIAL PRODUCTS (from Aarogya Nutri Mix) ──
  { id:13, name:'30 Days Slimming Kit', category:'Weight Management', catKey:'weight', emoji:'🌿', badge:'Best Seller', price:1399, mrp:1475, rating:4.89, reviews:156, desc:'100% Natural Slimming Kit for Healthy Weight Loss. Complete 30-day program with nutritional malts and supplements.', benefits:['100% Natural ingredients','30-day complete program','Supports healthy weight loss','No harmful chemicals','Includes diet plan guide'], tags:['Weight Loss','Slimming','Natural','30-Day Kit'] },
  { id:14, name:'15 Days Slimming Kit', category:'Weight Management', catKey:'weight', emoji:'🍃', badge:'Starter Pack', price:799, mrp:817, rating:4.82, reviews:89, desc:'100% Natural Slimming Kit for Healthy Weight Loss. Perfect starter kit for your weight management journey.', benefits:['15-day program','Natural weight management','Nutritional support','Easy to follow','Beginner friendly'], tags:['Weight Loss','Slimming','Natural','15-Day Kit'] },
  { id:15, name:'Sprouted Sathu Maavu Health Mix', category:'Health Mix', catKey:'health,immunity,bone,kids', emoji:'🌾', badge:'The Desi Protein', price:489, mrp:549, rating:4.85, reviews:203, desc:'Traditional South Indian health mix made from sprouted grains. Rich in protein, fiber, and essential nutrients.', benefits:['Made from sprouted grains','High protein content','Rich in fiber','Traditional recipe','Easy to prepare'], tags:['Health Mix','Protein','Sprouted Grains','Traditional'] },
  { id:16, name:'Veg Goat Leg Soup Mix', category:'Bone & Joint Health', catKey:'bone', emoji:'🦴', badge:'Bones & Joints Partner', price:299, mrp:349, rating:4.93, reviews:142, desc:'Mudavattukal Kilangu - Traditional vegetarian soup mix for bone and joint health. Natural calcium source.', benefits:['Supports bone health','Joint strength formula','100% vegetarian','Traditional Ayurvedic recipe','Natural calcium source'], tags:['Bone Health','Joint Support','Vegetarian','Ayurvedic'] },
  { id:17, name:'Weight Gain Porridge Mix', category:'Weight Management', catKey:'weight', emoji:'💪', badge:'Wholesome Calories', price:479, mrp:529, rating:4.87, reviews:118, desc:'Natural weight gain formula with wholesome calories. Rich in proteins, healthy fats, and essential nutrients.', benefits:['Healthy weight gain','High calorie formula','Rich in proteins','Natural ingredients','Easy to digest'], tags:['Weight Gain','Muscle Building','High Calorie','Natural'] },
  { id:18, name:'Nannari Sharbath Syrup', category:'Summer Essentials', catKey:'summer', emoji:'🥤', badge:'Your Body Coolant', price:329, mrp:399, rating:4.9, reviews:178, desc:'Traditional South Indian cooling drink. Made from Nannari roots, perfect for hot summer days. Natural body coolant.', benefits:['Natural body coolant','Made from Nannari roots','Refreshing taste','No artificial colors','Traditional recipe'], tags:['Summer Drink','Cooling','Natural','Traditional'] },
  { id:19, name:'Nalleru Kaaram Podi', category:'Traditional Spices', catKey:'spices', emoji:'🌶️', badge:'Bone & Joints Strength', price:199, mrp:249, rating:4.78, reviews:95, desc:'Traditional South Indian spice powder made from Nalleru (sesame) with special herbs. Supports bone and joint health.', benefits:['Rich in calcium','Supports joint health','Traditional recipe','Sesame-based formula','Perfect with rice & ghee'], tags:['Spice Powder','Bone Health','Traditional','South Indian'] },
  { id:20, name:'Herbal Hair Dye Natural Black', category:'Hair Care', catKey:'hair', emoji:'💇', badge:'Instant Natural Hair Dye', price:279, mrp:329, rating:4.88, reviews:167, desc:'100% herbal hair dye made from henna, indigo, neem, and hibiscus. Natural black color without chemicals.', benefits:['100% herbal formula','No harmful chemicals','Natural black color','Covers gray hair','Nourishes hair roots'], tags:['Hair Dye','Herbal','Chemical-Free','Natural Black'] },
  { id:21, name:'Dryfruit Laddu Dates Punch', category:'Healthy Snacks', catKey:'snacks', emoji:'🍬', badge:'Your Super Snack', price:619, mrp:699, rating:4.81, reviews:134, desc:'Healthy energy balls made from dates, dry fruits, and nuts. Pure cow ghee and natural sweetness. Perfect snack for all ages.', benefits:['Made with dates & dry fruits','Pure cow ghee','No refined sugar','Energy booster','Rich in iron & calcium'], tags:['Healthy Snack','Energy Balls','Dates','Dry Fruits'] },
  { id:22, name:'Weight Gain Combo Pack', category:'Weight Management', catKey:'weight', emoji:'🥛', badge:'Complete Combo', price:1449, mrp:1749, rating:4.89, reviews:87, desc:'Complete weight gain solution with porridge mix and dryfruit laddu. Natural and wholesome calories for healthy weight gain.', benefits:['Complete weight gain solution','Natural ingredients','High calorie combo','Protein rich','Tasty & nutritious'], tags:['Weight Gain','Combo Pack','High Calorie','Natural'] },
  { id:23, name:'Slimming Nutritional Malt', category:'Weight Management', catKey:'weight', emoji:'🥤', badge:'100% Natural', price:379, mrp:429, rating:4.88, reviews:156, desc:'100% Natural Slimming Malt powder. Supports metabolism and healthy weight loss. Rich in nutrients and fiber.', benefits:['Boosts metabolism','Supports weight loss','Rich in fiber','No artificial additives','Easy to consume'], tags:['Weight Loss','Malt','Natural','Metabolism Booster'] },
  
  // ── HEALTHY SNACKS COLLECTION ──
  { id:24, name:'Healthy Snacks Combo', category:'Healthy Snacks', catKey:'snacks', emoji:'🎁', badge:'Combo Pack', price:999, mrp:1247, rating:4.82, reviews:78, desc:'Complete healthy snacking solution with a variety of nutritious laddus and treats. Perfect for guilt-free everyday snacking.', benefits:['Variety of healthy snacks','Made with natural ingredients','No refined sugar','Energy boosting','Family pack'], tags:['Combo Pack','Healthy Snacks','Natural','Energy'] },
  { id:25, name:'Amla Candy', category:'Healthy Snacks', catKey:'snacks,immunity,amla', emoji:'🍭', badge:'All Time Favorite', price:259, mrp:299, rating:4.78, reviews:189, desc:'Natural dried amla candy packed with Vitamin C. Traditional Indian superfood candy for immunity and digestion.', benefits:['Rich in Vitamin C','Boosts immunity','Aids digestion','Natural ingredients','Tangy & sweet taste'], tags:['Amla','Vitamin C','Immunity','Candy'] },
  { id:26, name:'Gond Laddu', category:'Healthy Snacks', catKey:'snacks', emoji:'🥥', badge:'Postpartum Snack', price:599, mrp:699, rating:4.77, reviews:145, desc:'Traditional immunity-boosting sweets made with edible gum, pure cow ghee, almonds, and cashews. Perfect for new mothers.', benefits:['Made with pure cow ghee','Boosts immunity','Postpartum nutrition','Rich in protein','Traditional recipe'], tags:['Gond','Postpartum','Energy','Traditional'] },
  { id:27, name:'Omega 3 Laddu', category:'Healthy Snacks', catKey:'snacks', emoji:'🌰', badge:'Omega Rich', price:499, mrp:599, rating:4.65, reviews:98, desc:'Healthy flaxseed laddus rich in Omega 3 & 6 fatty acids. Made with pure cow ghee for brain health and heart wellness.', benefits:['Omega 3 & 6 rich','Made with flaxseeds','Pure cow ghee','Brain health','Heart health'], tags:['Omega 3','Flaxseed','Brain Health','Heart Health'] },
  { id:28, name:'Rice Bran Laddu', category:'Healthy Snacks', catKey:'snacks', emoji:'🍚', badge:'B12 Rich', price:419, mrp:499, rating:4.56, reviews:67, desc:'Vitamin B12-rich laddus made from rice bran. Sweeter way to get essential nutrients for energy and nervous system health.', benefits:['Rich in Vitamin B12','Energy booster','Nervous system support','Natural sweetness','Traditional recipe'], tags:['B12','Rice Bran','Energy','Healthy Sweet'] },
  { id:29, name:'Sunnundalu (Cow Ghee)', category:'Healthy Snacks', catKey:'snacks', emoji:'🥜', badge:'Andhra Favorite', price:519, mrp:599, rating:4.54, reviews:112, desc:'Traditional Andhra Pradesh favorite laddu made with urad dal and pure cow ghee. Rich in protein and energy.', benefits:['Made with pure cow ghee','High protein content','Traditional Andhra recipe','Energy rich','Delicious taste'], tags:['Sunnundalu','Andhra','Protein','Traditional'] },
  { id:30, name:'Sesame Dates Laddu', category:'Healthy Snacks', catKey:'snacks', emoji:'🫘', badge:'Calcium & Iron Rich', price:499, mrp:599, rating:4.5, reviews:89, desc:'Nutritious laddus combining sesame seeds and dates. Excellent source of calcium and iron for bone and blood health.', benefits:['Rich in calcium','High iron content','Made with dates','Bone health','Blood health'], tags:['Sesame','Dates','Calcium','Iron'] },
  
  // ── BONES STRENGTH COLLECTION ──
  { id:31, name:'Bones & Joints Strength Combo', category:'Bone & Joint Health', catKey:'bone', emoji:'💪', badge:'Complete Solution', price:749, mrp:947, rating:4.88, reviews:134, desc:'Comprehensive combo pack for bone and joint health. Contains multiple products to support skeletal strength and mobility.', benefits:['Complete bone care solution','Multiple products combo','Joint flexibility support','Natural ingredients','Value pack'], tags:['Bones','Joints','Combo','Health'] },
  { id:32, name:'Nalleru Pachadi', category:'Bone & Joint Health', catKey:'bone', emoji:'🌿', badge:'Bone Strength Partner', price:299, mrp:349, rating:4.76, reviews:87, desc:'Traditional sesame-based chutney powder for bone and joint strength. Rich in calcium and essential minerals.', benefits:['Rich in calcium','Supports joint health','Traditional recipe','Easy to use','Delicious taste'], tags:['Sesame','Bone Health','Traditional','Chutney'] },
  { id:33, name:'Moringa Sesame Kaaram Podi', category:'Traditional Spices', catKey:'spices', emoji:'🍃', badge:'Iron Rich', price:199, mrp:249, rating:4.76, reviews:92, desc:'Iron-rich spice powder combining moringa and sesame. Flavorful and nutritious addition to your meals.', benefits:['Rich in iron','Moringa superfood','Sesame calcium','Flavorful blend','Traditional taste'], tags:['Moringa','Sesame','Iron','Spice Powder'] },
  { id:34, name:'Siridanya Dosa Mix', category:'Healthy Foods', catKey:'health', emoji:'🥞', badge:'Traditional Taste', price:189, mrp:249, rating:5.0, reviews:45, desc:'Healthy grains dosa mix with traditional taste. Made from nutritious millets for a wholesome breakfast.', benefits:['Made from healthy grains','Traditional taste','Easy to prepare','Nutritious breakfast','Millet-based'], tags:['Dosa Mix','Millet','Healthy','Breakfast'] },
  { id:35, name:'Sesame Sunflower Kaaram Podi', category:'Traditional Spices', catKey:'spices', emoji:'🌻', badge:'Calcium Rich', price:199, mrp:249, rating:4.75, reviews:78, desc:'Calcium-rich spice powder with sesame and sunflower seeds. Flavorful and nutritious for bone health.', benefits:['Rich in calcium','Sesame & sunflower','Bone health support','Flavorful blend','Traditional preparation'], tags:['Sesame','Sunflower','Calcium','Spice'] },
  { id:36, name:'Moringa Curry Leaves Dosa Mix', category:'Healthy Foods', catKey:'health', emoji:'🥗', badge:'Superfood', price:229, mrp:279, rating:5.0, reviews:56, desc:'Superfood dosa mix combining moringa and curry leaves. Nutritious and flavorful breakfast option.', benefits:['Moringa superfood','Curry leaves antioxidants','Nutritious breakfast','Easy to prepare','Traditional taste'], tags:['Moringa','Dosa','Superfood','Healthy'] },
  { id:37, name:'Black Rice Urad Dal Porridge Mix', category:'Health Mix', catKey:'health', emoji:'⚫', badge:'Ancient Secret', price:199, mrp:229, rating:4.0, reviews:67, desc:'Ancient secret of strength combining black rice and urad dal. Rich in antioxidants and protein for energy and vitality.', benefits:['Black rice antioxidants','High protein from urad dal','Energy boosting','Ancient recipe','Nutrient dense'], tags:['Black Rice','Urad Dal','Protein','Porridge'] },
  
  // ── IMMUNITY BOOSTER COLLECTION ──
  { id:38, name:'Immunity Booster Kit', category:'Immunity', catKey:'immunity', emoji:'🛡️', badge:'Complete Protection', price:1111, mrp:1476, rating:4.9, reviews:198, desc:'Complete immunity strengthening kit with herbal teas, health mixes, and natural supplements. Build strong immunity naturally.', benefits:['Complete immunity kit','Multiple products','Herbal formulations','Natural protection','Value combo'], tags:['Immunity','Kit','Herbal','Protection'] },
  { id:39, name:'Moringa Powder', category:'Immunity', catKey:'immunity', emoji:'🌿', badge:'Pure Greens', price:179, mrp:219, rating:5.0, reviews:145, desc:'Pure moringa powder packed with vitamins and minerals. Everyday vitality booster for complete nutrition and immunity.', benefits:['Rich in vitamins & minerals','Boosts immunity','Pure moringa leaves','Natural energy','Daily wellness'], tags:['Moringa','Superfood','Immunity','Vitamins'] },
  { id:40, name:'Herbal Tea Immunity Blend', category:'Tea Blends', catKey:'tea', emoji:'☕', badge:'Adults Immunity', price:299, mrp:379, rating:4.55, reviews:112, desc:'Immunity-boosting herbal tea blend for adults. Contains turmeric, cinnamon, and traditional herbs for wellness.', benefits:['Boosts immunity','Herbal ingredients','No caffeine','Warming spices','Daily wellness'], tags:['Herbal Tea','Immunity','Adults','Wellness'] },
  { id:41, name:'Immune-O-Boost Tulsi Tea', category:'Tea Blends', catKey:'tea', emoji:'🍵', badge:'Kids Immunity', price:279, mrp:329, rating:4.8, reviews:98, desc:'Special tulsi-based immunity tea for kids. Gentle yet effective herbal blend to strengthen children\'s immune system.', benefits:['Perfect for kids','Tulsi based','Boosts immunity','Pleasant taste','No harsh ingredients'], tags:['Tulsi','Kids','Immunity','Tea'] },
  { id:42, name:'Sukku Malli Coffee Powder', category:'Immunity', catKey:'immunity', emoji:'☕', badge:'No Caffeine', price:199, mrp:249, rating:4.7, reviews:87, desc:'Traditional caffeine-free coffee alternative made with dry ginger and coriander. Warming and digestive.', benefits:['Zero caffeine','Dry ginger benefits','Aids digestion','Traditional recipe','Warming drink'], tags:['Coffee Alternative','Caffeine Free','Digestive','Traditional'] },
  { id:43, name:'Guava Leaves Powder', category:'Immunity', catKey:'immunity', emoji:'🍃', badge:'Blood Sugar Support', price:199, mrp:249, rating:4.6, reviews:76, desc:'Natural guava leaves powder to help lower blood sugar and HbA1c levels. Traditional remedy for metabolic health.', benefits:['Supports blood sugar control','May lower HbA1c','Natural remedy','Guava leaves extract','Daily wellness'], tags:['Guava Leaves','Blood Sugar','Herbal','Diabetic Care'] },
  
  // ── KIDS SPECIAL COLLECTION ──
  { id:44, name:'Super Kid Combo', category:'Kids Nutrition', catKey:'kids', emoji:'🌟', badge:'Complete Kid Pack', price:999, mrp:1247, rating:4.84, reviews:167, desc:'Complete nutrition combo for super kids. Includes health mix, snacks, and supplements for growing children.', benefits:['Complete nutrition kit','Multiple products','Perfect for kids','Growth support','Tasty & healthy'], tags:['Kids','Combo','Nutrition','Growth'] },
  { id:45, name:'ABC Malt', category:'Kids Nutrition', catKey:'kids,malts', emoji:'🥕', badge:'All-in-One', price:349, mrp:399, rating:4.86, reviews:189, desc:'All-in-One malt with Amla, Beetroot, and Carrot goodness. Complete nutrition for kids with natural ingredients.', benefits:['Amla, Beetroot, Carrot','Rich in vitamins','Boosts immunity','Natural ingredients','Kids love it'], tags:['ABC','Malt','Kids','Immunity'] },
  { id:46, name:'Baby Bath Powder (Sunni Pindi)', category:'Baby Care', catKey:'babycare', emoji:'🧴', badge:'Baby Skin Nourisher', price:149, mrp:199, rating:4.5, reviews:134, desc:'Traditional baby bath powder for gentle cleansing and skin nourishment. Safe and natural for delicate baby skin.', benefits:['Gentle on baby skin','Natural ingredients','Traditional formula','Nourishes skin','Chemical-free'], tags:['Baby Care','Bath Powder','Natural','Gentle'] },
  { id:47, name:'Panchagavya Tooth Powder', category:'Oral Care', catKey:'oralcare', emoji:'🦷', badge:'Traditional Care', price:199, mrp:229, rating:4.8, reviews:98, desc:'Traditional ayurvedic tooth powder with Panchagavya. Natural dental care for healthy teeth and gums.', benefits:['Traditional Ayurvedic','Natural ingredients','Healthy teeth & gums','Chemical-free','Fresh breath'], tags:['Tooth Powder','Ayurvedic','Natural','Oral Care'] },
  { id:48, name:'Multi Millet Penne Pasta', category:'Healthy Foods', catKey:'health', emoji:'🍝', badge:'Healthy Twist', price:119, mrp:159, rating:4.7, reviews:87, desc:'Healthy millet-based penne pasta. Nutritious alternative to regular pasta for kids and families.', benefits:['Made from millets','Healthier than wheat pasta','Good for kids','Easy to cook','Delicious taste'], tags:['Millet','Pasta','Kids','Healthy'] },
  { id:49, name:'Sprouted Ragi Choco Malt', category:'Kids Nutrition', catKey:'kids', emoji:'🍫', badge:'Chocolate Twist', price:249, mrp:299, rating:4.8, reviews:145, desc:'Delicious chocolate-flavored malt with sprouted ragi. Perfect combination of taste and nutrition for kids.', benefits:['Chocolate flavor kids love','Sprouted ragi nutrition','Calcium rich','Energy booster','Tasty & healthy'], tags:['Ragi','Chocolate','Kids','Malt'] },
  { id:50, name:'Little Millet Macaroni Pasta', category:'Healthy Foods', catKey:'health', emoji:'🍝', badge:'Millet Twist', price:119, mrp:159, rating:4.6, reviews:76, desc:'Macaroni pasta made from nutritious little millet. Healthy twist on kids\' favorite pasta.', benefits:['Little millet based','Healthier option','Perfect for kids','Easy to prepare','Nutritious meal'], tags:['Millet','Macaroni','Kids','Healthy'] },
  { id:51, name:'Dry Fruit Powder', category:'Kids Nutrition', catKey:'kids', emoji:'🥜', badge:'Super Mix', price:249, mrp:299, rating:5.0, reviews:123, desc:'Premium dry fruit super mix powder with almonds, cashews, and more. Instant nutrition booster for kids.', benefits:['Premium dry fruits','Rich in nutrients','Boosts brain power','Natural energy','Easy to consume'], tags:['Dry Fruits','Kids','Nutrition','Brain Food'] },
  { id:52, name:'Triphala Powder', category:'Herbal Supplements', catKey:'herbal', emoji:'🌿', badge:'Digestive Aid', price:149, mrp:199, rating:4.7, reviews:98, desc:'Classic Ayurvedic Triphala powder for digestion and gastric issues. Gentle detox for whole family.', benefits:['Aids digestion','Helps gastric issues','Gentle detox','Ayurvedic formula','Family safe'], tags:['Triphala','Digestion','Ayurvedic','Detox'] },
  { id:53, name:'Foxtail Millet Vermicelli', category:'Healthy Foods', catKey:'health', emoji:'🍜', badge:'Millet Twist', price:99, mrp:149, rating:4.6, reviews:89, desc:'Healthy vermicelli made from foxtail millet. Nutritious alternative for breakfast and snacks.', benefits:['Foxtail millet based','Low glycemic index','Easy to prepare','Healthy breakfast','Diabetic friendly'], tags:['Millet','Vermicelli','Healthy','Breakfast'] },
  { id:54, name:'Power Seed Mix (7 in 1)', category:'Healthy Snacks', catKey:'snacks', emoji:'🌰', badge:'Energy Booster', price:219, mrp:269, rating:4.8, reviews:112, desc:'Sand-roasted power seed mix with 7 nutritious seeds. Instant energy booster and healthy snack.', benefits:['7 types of seeds','Sand roasted','Instant energy','Nutrient dense','Crunchy & tasty'], tags:['Seeds','Energy','Healthy Snack','Natural'] },
  { id:55, name:'Red Banana Malt', category:'Kids Nutrition', catKey:'kids,malts', emoji:'🍌', badge:'Weight Gain', price:299, mrp:349, rating:4.51, reviews:94, desc:'Special malt made from red bananas to help healthy weight gain in kids. Natural and nutritious.', benefits:['Made from red bananas','Helps weight gain','Natural ingredients','Rich in nutrients','Kids friendly'], tags:['Red Banana','Weight Gain','Kids','Malt'] },
  { id:56, name:'Beetroot Malt', category:'Kids Nutrition', catKey:'kids,malts', emoji:'❤️', badge:'Haemoglobin Booster', price:299, mrp:349, rating:4.7, reviews:145, desc:'Beetroot malt to improve haemoglobin levels naturally. Perfect for kids with iron deficiency.', benefits:['Improves haemoglobin','Rich in iron','Natural beetroot','Energy booster','Tasty for kids'], tags:['Beetroot','Iron','Haemoglobin','Kids'] },
  { id:57, name:'Beetroot Amla', category:'Healthy Snacks', catKey:'snacks,amla', emoji:'💗', badge:'Flavourful Chat', price:149, mrp:199, rating:4.6, reviews:78, desc:'Tangy and flavourful chat-pata snack combining beetroot and amla. Healthy munching option.', benefits:['Beetroot & amla goodness','Tangy taste','Vitamin C rich','Iron rich','Healthy snack'], tags:['Beetroot','Amla','Snack','Tangy'] },
  
  // ── MALTS COLLECTION (New Products) ──
  { id:58, name:'Carrot Malt', category:'Kids Nutrition', catKey:'kids,malts', emoji:'🥕', badge:'Vitamin A Rich', price:299, mrp:349, rating:4.45, reviews:87, desc:'Carrot malt rich in Vitamin A for eye health and overall immunity. Delicious and nutritious for growing kids.', benefits:['Rich in Vitamin A','Eye health support','Boosts immunity','Carrot goodness','Kids friendly'], tags:['Carrot','Malt','Vitamin A','Kids'] },
  
  // ── MAKHANA COLLECTION ──
  { id:59, name:'Moringa Sesame Makhana', category:'Healthy Snacks', catKey:'snacks,makhana', emoji:'🌿', badge:'Unique Flavour', price:199, mrp:249, rating:4.81, reviews:123, desc:'World\'s unique flavoured makhana with moringa and sesame. Crunchy, nutritious, and packed with superfood goodness.', benefits:['Moringa superfood','Sesame calcium','Crunchy texture','Low calorie snack','Protein rich'], tags:['Makhana','Moringa','Sesame','Healthy Snack'] },
  { id:60, name:'Almond Curry Leaves Makhana', category:'Healthy Snacks', catKey:'snacks,makhana', emoji:'🍃', badge:'Unique Flavour', price:199, mrp:249, rating:4.62, reviews:98, desc:'World\'s unique flavoured makhana with almond and curry leaves. Perfect combination of taste and nutrition.', benefits:['Almond protein','Curry leaves antioxidants','Crunchy & tasty','Low calorie','Guilt-free snacking'], tags:['Makhana','Almond','Curry Leaves','Healthy Snack'] },
  { id:61, name:'Pumpkin Flax Seeds Makhana', category:'Healthy Snacks', catKey:'snacks,makhana', emoji:'🎃', badge:'Unique Flavour', price:199, mrp:249, rating:4.51, reviews:87, desc:'World\'s unique flavoured makhana with pumpkin and flax seeds. Omega-rich crunchy snack for healthy munching.', benefits:['Pumpkin seeds nutrition','Flax seeds omega-3','Crunchy texture','Heart healthy','Low calorie'], tags:['Makhana','Pumpkin Seeds','Flax Seeds','Healthy Snack'] },
  
  // ── AMLA SANJEEVANI COLLECTION ──
  { id:62, name:'Amla Powder', category:'Immunity', catKey:'immunity,amla', emoji:'🍋', badge:'Human Sanjeevani', price:259, mrp:299, rating:5.0, reviews:134, desc:'Pure amla powder - the human sanjeevani. Rich in Vitamin C and natural antioxidants for complete wellness.', benefits:['Rich in Vitamin C','Boosts immunity','Antioxidant rich','Supports digestion','Hair & skin health'], tags:['Amla','Vitamin C','Immunity','Ayurvedic'] },
  
  // ── INSTANT PREMIXES COLLECTION ──
  { id:63, name:'Beetroot Dosa Mix', category:'Instant Premixes', catKey:'instant', emoji:'🥞', badge:'Iron Rich', price:229, mrp:279, rating:5.0, reviews:67, desc:'Iron-rich dosa mix with beetroot. Healthy and delicious breakfast option with natural beetroot goodness.', benefits:['Rich in iron','Beetroot nutrition','Easy to prepare','Healthy breakfast','Traditional taste'], tags:['Dosa','Beetroot','Iron','Instant Mix'] },
  { id:64, name:'Finger Millet Pongal Premix', category:'Instant Premixes', catKey:'instant', emoji:'🍚', badge:'All Time Favourite', price:249, mrp:299, rating:4.8, reviews:89, desc:'All-time favourite breakfast pongal made with finger millet. Nutritious and delicious instant meal.', benefits:['Finger millet nutrition','Easy to prepare','Traditional taste','Diabetic friendly','High in calcium'], tags:['Pongal','Millet','Instant','Breakfast'] },
  { id:65, name:'Wheat Ravva Upma Premix', category:'Instant Premixes', catKey:'instant', emoji:'🥣', badge:'Delicious Staple', price:249, mrp:299, rating:4.75, reviews:78, desc:'Deliciousness of staple wheat ravva upma in instant form. Quick, easy, and tasty breakfast solution.', benefits:['Wheat nutrition','Ready in minutes','Delicious taste','Healthy breakfast','Traditional flavour'], tags:['Upma','Wheat','Instant','Breakfast'] },
  { id:66, name:'Coconut Chutney Premix', category:'Instant Premixes', catKey:'instant', emoji:'🥥', badge:'Goes With All', price:189, mrp:249, rating:4.7, reviews:92, desc:'Instant coconut chutney premix that goes with all breakfasts. Authentic South Indian taste in minutes.', benefits:['Authentic coconut taste','Instant preparation','Goes with dosa, idli','Traditional recipe','No preservatives'], tags:['Chutney','Coconut','Instant','South Indian'] },
  
  // ── COOKING ESSENTIALS COLLECTION ──
  { id:67, name:'Lakadong Turmeric Powder', category:'Cooking Essentials', catKey:'cooking', emoji:'🌟', badge:'Higher Curcumin', price:229, mrp:279, rating:4.86, reviews:145, desc:'Single origin Lakadong turmeric powder with higher curcumin content. Premium quality for health and cooking.', benefits:['Higher curcumin','Single origin','Anti-inflammatory','Pure & natural','Premium quality'], tags:['Turmeric','Lakadong','Cooking','Curcumin'] },
  { id:68, name:'Kashmiri Mongra Saffron', category:'Cooking Essentials', catKey:'cooking', emoji:'🧡', badge:'A++ Grade', price:499, mrp:549, rating:4.86, reviews:112, desc:'Single origin A++ grade Kashmiri Mongra Saffron. Premium quality threads for authentic aroma and flavour.', benefits:['A++ grade quality','Kashmiri Mongra','Premium threads','Rich aroma','Single origin'], tags:['Saffron','Kashmiri','Premium','Cooking'] },
  { id:69, name:'Kura Karam Masala Chilli Powder', category:'Cooking Essentials', catKey:'cooking,spices', emoji:'🌶️', badge:'Aromatic Blend', price:159, mrp:219, rating:5.0, reviews:98, desc:'Aromatic and flavourful masala chilli powder blend. Perfect spice mix for authentic South Indian curries.', benefits:['Aromatic blend','Perfect spice level','Traditional recipe','No artificial colours','Fresh ground'], tags:['Chilli Powder','Masala','Spices','South Indian'] },
  { id:70, name:'Multi Floral Honey', category:'Cooking Essentials', catKey:'cooking', emoji:'🍯', badge:'Natural Sweetness', price:399, mrp:449, rating:4.8, reviews:87, desc:'Naturally sourced multi-floral honey from nature. Pure, raw, and unprocessed for maximum health benefits.', benefits:['100% pure honey','Multi-floral','Raw & unprocessed','Natural sweetness','Antioxidant rich'], tags:['Honey','Natural','Pure','Sweetener'] },
  { id:71, name:'Organic Jaggery Powder', category:'Cooking Essentials', catKey:'cooking', emoji:'🍬', badge:'Natural Goodness', price:149, mrp:179, rating:4.75, reviews:76, desc:'Organic sugarcane jaggery powder - the goodness of nature. Healthy alternative to refined sugar.', benefits:['Organic sugarcane','Unrefined sweetener','Rich in minerals','Iron rich','Natural taste'], tags:['Jaggery','Organic','Natural','Sweetener'] },
  { id:72, name:'Dry Dates Powder', category:'Cooking Essentials', catKey:'cooking', emoji:'📅', badge:'Natural Energy', price:179, mrp:229, rating:4.7, reviews:89, desc:'Natural energy and everyday strength from dry dates powder. Healthy sweetener and nutrition booster.', benefits:['Natural sweetener','Energy booster','Rich in iron','No added sugar','Nutrient dense'], tags:['Dates','Powder','Natural','Energy'] },
  { id:73, name:'Turmeric Powder', category:'Cooking Essentials', catKey:'cooking,spices', emoji:'💛', badge:'Nature\'s Goodness', price:319, mrp:349, rating:4.84, reviews:134, desc:'Pure turmeric powder - goodness of nature. Essential spice for daily cooking and health benefits.', benefits:['Pure turmeric','Anti-inflammatory','Daily wellness','Rich color','Fresh ground'], tags:['Turmeric','Spices','Cooking','Natural'] },
  { id:74, name:'Red Chilli Powder', category:'Cooking Essentials', catKey:'cooking,spices', emoji:'🔥', badge:'Hotness Packed', price:319, mrp:349, rating:4.84, reviews:98, desc:'Hotness packed red chilli powder. Pure, vibrant, and flavorful for authentic spicy dishes.', benefits:['Pure chilli','Perfect heat level','Vibrant color','Fresh ground','No additives'], tags:['Chilli','Spices','Cooking','Hot'] },
  { id:75, name:'Amchur Powder', category:'Cooking Essentials', catKey:'cooking,spices', emoji:'🥭', badge:'Raw Mango', price:149, mrp:199, rating:4.65, reviews:67, desc:'Goodness of raw mango in powder form. Tangy flavor enhancer for North Indian dishes.', benefits:['Raw mango powder','Tangy flavour','Digestive aid','Vitamin C rich','Traditional spice'], tags:['Amchur','Mango','Spices','Tangy'] },
  { id:76, name:'Mango Orugulu (Dry Mango Pieces)', category:'Cooking Essentials', catKey:'cooking', emoji:'🍋', badge:'Raw Mango', price:149, mrp:199, rating:4.6, reviews:78, desc:'Goodness of raw mango in dried pieces. Traditional pickle ingredient and tangy snack.', benefits:['Dried mango pieces','Tangy taste','Pickle ingredient','Vitamin C','Traditional'], tags:['Mango','Dried Fruit','Cooking','Tangy'] },
  { id:77, name:'Organic Black Pepper Powder', category:'Cooking Essentials', catKey:'cooking,spices', emoji:'⚫', badge:'Freshness Packed', price:179, mrp:229, rating:4.7, reviews:89, desc:'Freshness packed organic black pepper powder. Premium quality for maximum flavor and health benefits.', benefits:['Organic pepper','Freshly ground','Rich aroma','Digestive aid','Premium quality'], tags:['Black Pepper','Organic','Spices','Fresh'] },
  { id:78, name:'Organic Black Pepper Whole', category:'Cooking Essentials', catKey:'cooking,spices', emoji:'⚫', badge:'Flavourful', price:149, mrp:189, rating:4.65, reviews:76, desc:'Flavourful packed organic black pepper whole. Premium whole peppercorns for grinding fresh.', benefits:['Whole peppercorns','Organic quality','Fresh grinding','Rich flavor','Premium grade'], tags:['Black Pepper','Whole','Organic','Spices'] },
  { id:79, name:'Sprouted Fenugreek Powder', category:'Cooking Essentials', catKey:'cooking', emoji:'🌱', badge:'Diabetic Cure', price:149, mrp:199, rating:4.6, reviews:67, desc:'Sprouted fenugreek powder for diabetic care. Natural blood sugar management with enhanced nutrition.', benefits:['Sprouted fenugreek','Blood sugar control','Diabetic friendly','Easy to consume','Enhanced nutrition'], tags:['Fenugreek','Sprouted','Diabetic','Health'] },
  { id:80, name:'Gond Katira', category:'Cooking Essentials', catKey:'cooking', emoji:'🌳', badge:'Natural Tree Gum', price:119, mrp:149, rating:4.8, reviews:92, desc:'Natural tree gum for cooling drinks and desserts. Traditional ingredient for summer wellness.', benefits:['Natural tree gum','Body coolant','Summer special','Traditional ingredient','Digestive aid'], tags:['Gond Katira','Natural','Cooling','Traditional'] },
  
  // ── GENERAL HEALTH COLLECTION (New Products not already in data.js) ──
  { id:81, name:'Sea Buckthorn Dried', category:'Immunity', catKey:'immunity,health', emoji:'🍊', badge:'Superfruit', price:299, mrp:349, rating:4.86, reviews:134, desc:'Rich nutrition from nature\'s superfruit - dried sea buckthorn berries. Packed with Omega 3, 6, 7, 9 and Vitamin C.', benefits:['Omega 3,6,7,9 rich','High Vitamin C','Antioxidant superfruit','Boosts immunity','Natural energy'], tags:['Sea Buckthorn','Superfruit','Omega','Immunity'] },
  { id:82, name:'ABC Powder (Amla Beetroot Carrot)', category:'General Health', catKey:'health,immunity', emoji:'🥕', badge:'Triple Goodness', price:279, mrp:329, rating:4.83, reviews:145, desc:'Amla, beetroot, and carrot goodness in one powder. Complete nutrition for immunity, energy, and vitality.', benefits:['Vitamin C from amla','Iron from beetroot','Vitamin A from carrot','Boosts immunity','Natural energy'], tags:['ABC','Powder','Immunity','Nutrition'] },
  { id:83, name:'Diabetic Health Mix', category:'Health Mix', catKey:'health', emoji:'🌾', badge:'Diabetic Friendly', price:489, mrp:549, rating:4.9, reviews:167, desc:'Energy-boosting diabetic-friendly health mix. Low glycemic index formula for sustained energy without sugar spikes.', benefits:['Diabetic friendly','Low glycemic index','Energy boosting','High fiber','No added sugar'], tags:['Diabetic','Health Mix','Energy','Low GI'] },
  { id:84, name:'Mango Seeds Powder', category:'General Health', catKey:'health', emoji:'🥭', badge:'B12 Source', price:149, mrp:189, rating:4.57, reviews:78, desc:'Your daily dose of Vitamin B12 from mango seeds powder. Sustainable nutrition from natural sources.', benefits:['Rich in Vitamin B12','Sustainable source','Energy booster','Supports metabolism','Natural ingredient'], tags:['Mango Seeds','B12','Energy','Natural'] },
  { id:85, name:'Diabetic Control Powder', category:'General Health', catKey:'health', emoji:'📊', badge:'HbA1c Control', price:249, mrp:299, rating:5.0, reviews:89, desc:'Controls HbA1c levels naturally. Herbal blend for blood sugar management and diabetic wellness.', benefits:['Controls HbA1c','Blood sugar support','Herbal formula','Natural ingredients','Daily wellness'], tags:['Diabetic','Blood Sugar','Herbal','Control'] },
  { id:86, name:'ABCD Powder (Amla Beetroot Carrot Dry Dates)', category:'General Health', catKey:'health,immunity', emoji:'🍇', badge:'Quad Power', price:299, mrp:349, rating:4.77, reviews:123, desc:'Amla, beetroot, carrot, and dry dates combined. Enhanced nutrition with natural sweetness and energy.', benefits:['Four superfoods','Natural sweetness','Energy boosting','Rich in nutrients','Immunity support'], tags:['ABCD','Powder','Nutrition','Energy'] },
  { id:87, name:'Wheat Grass Powder', category:'General Health', catKey:'health', emoji:'🌱', badge:'Daily Detox', price:199, mrp:229, rating:4.7, reviews:87, desc:'Fresh greens for daily detox. Pure wheat grass powder for cleansing and natural energy boost.', benefits:['Detoxifying','Rich in chlorophyll','Alkalizing','Energy booster','Antioxidant rich'], tags:['Wheat Grass','Detox','Greens','Natural'] },
  { id:88, name:'Rice Bran Powder', category:'General Health', catKey:'health', emoji:'🌾', badge:'Heart Friendly', price:149, mrp:179, rating:4.65, reviews:76, desc:'Fiber-rich and heart-friendly rice bran powder. Natural source of B vitamins and healthy fats.', benefits:['High fiber','Heart healthy','Rich in B vitamins','Cholesterol support','Natural nutrition'], tags:['Rice Bran','Fiber','Heart Health','B Vitamins'] },
  { id:89, name:'Dry Ginger Powder (Sonti Podi)', category:'General Health', catKey:'health,constipation', emoji:'🫚', badge:'Digestion Aid', price:99, mrp:149, rating:4.6, reviews:67, desc:'Natural remedy for cold and improves digestion. Traditional dry ginger powder for wellness.', benefits:['Improves digestion','Cold remedy','Anti-inflammatory','Warming spice','Traditional medicine'], tags:['Ginger','Digestion','Natural','Traditional'] },
  { id:90, name:'Seed Cycling Kit', category:'Women Health', catKey:'health', emoji:'🌰', badge:'Period Solution', price:619, mrp:749, rating:4.91, reviews:156, desc:'Solution for irregular periods through natural seed cycling. Complete kit for hormonal balance.', benefits:['Balances hormones','Regulates periods','Natural method','Complete kit','Easy to follow'], tags:['Seed Cycling','Women Health','Hormones','Periods'] },
  { id:91, name:'Curry Leaves Powder', category:'Cooking Essentials', catKey:'cooking,health', emoji:'🍃', badge:'Healthy Flavour', price:169, mrp:199, rating:4.7, reviews:89, desc:'Healthy and flavourful meal enhancer. Curry leaves powder for nutrition and authentic South Indian taste.', benefits:['Rich in antioxidants','Hair health','Digestive aid','Traditional flavour','Nutrient dense'], tags:['Curry Leaves','Healthy','Flavour','Cooking'] },
  { id:92, name:'DeBloat Powder', category:'Digestive Health', catKey:'health,constipation', emoji:'🌿', badge:'Gas Relief', price:199, mrp:229, rating:4.6, reviews:78, desc:'Eliminate excess gas, bloat, burps, and discomfort. Natural herbal blend for digestive wellness.', benefits:['Reduces bloating','Gas relief','Improves digestion','Natural herbs','Fast acting'], tags:['Digestive','Bloating','Gas Relief','Herbal'] },
  { id:93, name:'LactoBoost Health Mix', category:'Women Health', catKey:'health', emoji:'🤱', badge:'Lactation Support', price:299, mrp:349, rating:4.75, reviews:92, desc:'Lactating mothers special health mix. Supports milk production and postpartum nutrition naturally.', benefits:['Boosts lactation','Postpartum nutrition','Natural galactagogue','Energy for mothers','Traditional recipe'], tags:['Lactation','Postpartum','Women Health','Nutrition'] },
  
  // ── CONSTIPATION COLLECTION ──
  { id:94, name:'Slim-Tox Tea (Slimming & Detox)', category:'Tea Blends', catKey:'tea,constipation', emoji:'☕', badge:'Gut Health', price:279, mrp:329, rating:4.6, reviews:98, desc:'Your gut health specialist! Herbal tea blend for slimming, detox, and digestive wellness.', benefits:['Aids weight loss','Detoxifies body','Improves digestion','Relieves constipation','Herbal blend'], tags:['Tea','Detox','Slimming','Digestion'] }
];
